#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/nlhtree_py
  
  rm -rf build/* 
  
  runpysloc -L py nlh_check_in_data_dir nlh_check_in_u_dir nlh_populate_data_dir nlh_save_to_u_dir  -X cover -X htmlcov -X dist -X tmp -v $@
else
  echo "DEV_BASE is not defined"
fi
