#!/usr/bin/python3

# ~/dev/py/nlhtree_py/nlhSaveToUDir

import os
import re
import sys
import time
from argparse import ArgumentParser

from nlhtree import (__version__, __version_date__,
                     NLHTree,
                     )


def main():

    pathToInit = os.path.join('nlhtree', '__init__.py')
    version = re.search("__version__\s*=\s*'(.*)'",
                        open(pathToInit).read()).group(1)
    versionDate = re.search("__version_date__\s*=\s*'(.*)'",
                            open(pathToInit).read()).group(1)

    appName = 'nlhSaveToUDir %s' % __version__
    UDIR = os.environ['DVCZ_UDIR']

    # parse the command line ----------------------------------------
    DESC   = \
        'given a project directory, write an NLHTree while backing the project up to U'

    parser = ArgumentParser(description=DESC)

    parser.add_argument('-1', '--usingSHA1', action='store_true',
                        help='using the 160-bit SHA1 hash')

    parser.add_argument('-b', '--listFile', default='list.nlh',
                        help='where to write listing (default = list.nlh)')

    parser.add_argument('-d', '--dataDir', default='.',
                        help='path to data directory')

    parser.add_argument('-j', '--justShow', action='store_true',
                        help='show options and exit')

    parser.add_argument('-T', '--testing', action='store_true',
                        help='this is a test run')

    parser.add_argument('-u', '--uDir', default=UDIR,
                        help='path to uDir')

    parser.add_argument('-V', '--showVersion', action='store_true',
                        help='print the version number and exit')

    parser.add_argument('-v', '--verbose', action='store_true',
                        help='be chatty')

    parser.add_argument('-z', '--dontDoIt', action='store_true',
                        help="don't actually do anything, just say what you would do")

    args = parser.parse_args()

    if args.showVersion:
        print(appName)
        sys.exit(0)

    # fixups --------------------------------------------------------

    if args.testing:
        # output appears under tmp/
        # XXX this should be fixed to interpose # a random directory name
        #   that is not already in use
        # XXX This behavior needs to be clearly documented.
        listFile = os.path.join('tmp', listFile)
        if args.uDir[0] == '/':
            args.uDir = args.uDir[1:]
        args.uDir = os.path.join('tmp', args.uDir)

    # sanity checks -------------------------------------------------

    if not (args.testing or args.justShow):
        if not os.path.exists(args.dataDir):
            print("%s does not exist; cannot continue" % args.dataDir)
            sys.exit(1)
    if not args.justShow:
        os.makedirs(os.path.join(args.uDir, 'in'), mode=0o755, exist_ok=True)
        os.makedirs(os.path.join(args.uDir, 'tmp'), mode=0o755, exist_ok=True)

    # complete setup ------------------------------------------------

    if args.verbose or args.justShow:
        print("%s %s" % (appName, __version_date__))

    if args.verbose or args.justShow:
        print('dataDir          = ' + str(args.dataDir))
        print('dontDoIt         = ' + str(args.dontDoIt))
        print('justShow         = ' + str(args.justShow))
        print('listFile         = ' + str(args.listFile))
        print('showVersion      = ' + str(args.showVersion))
        print('testing          = ' + str(args.testing))
        print('uDir             = ' + str(args.uDir))
        print('usingSHA1        = ' + str(args.usingSHA1))
        print('verbose          = ' + str(args.verbose))

    # do what's required --------------------------------------------
    if not args.justShow:
        if args.dontDoIt:
            print("would be saving %s to %s and writing a listing to %s" % (
                args.dataDir, args.uDir, args.listFile))
        else:
            NLHTree.saveToUDir(args.dataDir, args.uDir, args.listFile)

if __name__ == '__main__':
    main()
