#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/nlhtree_py
  
  autopep8 -air src/nlhtree tests
  autopep8 -ai src/nlh_check_in_data_dir src/nlh_check_in_u_dir \
               src/nlh_populate_data_dir src/nlh_save_to_u_dir 
  echo "not styling example1/ subdir"
  echo "not styling example2/ subdir"
  echo "not styling example3/ subdir"
  echo "not styling test/ subdir"
  
else
  echo "DEV_BASE is not defined"
fi
