#!/usr/bin/python3
# ~/dev/py/nlhtree_py/nlhSaveToUDir

""" Save an NLHTree into a content-keyed store. """

import os
import sys
from argparse import ArgumentParser

from optionz import dump_options
from nlhtree import (__version__, __version_date__, NLHTree)
from xlattice import(check_hashtype, parse_hashtype_etc, fix_hashtype,
                     show_hashtype_etc, check_u_path)


def main():
    """ Save an NLHTree into a content-keyed store. """

    app_name = 'nlhSaveToUDir %s' % __version__
    # UDIR = os.environ['DVCZ_UDIR']    # unused

    # parse the command line ----------------------------------------
    desc =\
        'given a project directory, write an NLHTree while backing the project up to U'

    parser = ArgumentParser(description=desc)

    parser.add_argument('-b', '--list_file', default='list.nlh',
                        help='where to write listing (default = list.nlh)')

    parser.add_argument('-d', '--dataDir', default='.',
                        help='path to data directory')

    parser.add_argument('-I', '--using_indir', action='store_true',
                        help='show options and exit')

    parser.add_argument('-j', '--justShow', action='store_true',
                        help='show options and exit')

    parser.add_argument('-T', '--testing', action='store_true',
                        help='this is a test run')

    parser.add_argument('-V', '--showVersion', action='store_true',
                        help='print the version number and exit')

    parser.add_argument('-z', '--dontDoIt', action='store_true',
                        help="don't actually do anything, just say what you would do")
    parse_hashtype_etc(parser)
    args = parser.parse_args()

    if args.showVersion:
        print(app_name)
        sys.exit(0)

    # fixups --------------------------------------------------------
    fix_hashtype(args)
    if args.testing:
        # output appears under tmp/
        # XXX this should be fixed to interpose # a random directory name
        #   that is not already in use
        # XXX This behavior needs to be clearly documented.
        args.list_file = os.path.join('tmp', args.list_file)
        if args.u_path[0] == '/':
            args.u_path = args.u_path[1:]
        args.u_path = os.path.join('tmp', args.u_path)

    # sanity checks -------------------------------------------------
    check_hashtype(args.hashtype)
    if not (args.testing or args.justShow):
        if not os.path.exists(args.dataDir):
            print("%s does not exist; cannot continue" % args.dataDir)
            sys.exit(1)
    if not args.justShow:
        check_u_path(parser, args, must_exist=False)
        os.makedirs(os.path.join(args.u_path, 'in'), mode=0o755, exist_ok=True)
        os.makedirs(
            os.path.join(
                args.u_path,
                'tmp'),
            mode=0o755,
            exist_ok=True)

    # complete setup ------------------------------------------------

    if args.verbose or args.justShow:
        print("%s %s" % (app_name, __version_date__))

    if args.verbose or args.justShow:
        print(dump_options(args))

    # do what's required --------------------------------------------
    if not args.justShow:
        if args.dontDoIt:
            print("would be saving %s to %s and writing a listing to %s" % (
                args.dataDir, args.u_path, args.list_file))
        else:
            tree = NLHTree.create_from_file_system(args.dataDir, args.hashtype)
            with open(args.list_file, 'w+') as file:
                file.write(tree.__str__())
            tree.save_to_u_dir(args.dataDir, args.u_path, args.using_indir)


if __name__ == '__main__':
    main()
